var TAG_BODY = 'body';
var TAG_UN_ORDERED_LIST = "ul";
var TAG_LIST_ITEM = "li";
var TAG_DIV = "div";
var TAG_SVG = "svg";
var TAG_SVG_G = 'g';
var TAG_SVG_TEXT = 'text';
var TAG_SVG_PATH = 'path';
var TAG_CIRCLE = 'circle';
var TAG_HEADER_ONE = 'h1';
var TAG_HEADER_SIX = 'h6';
var TAG_HEADER_SEVEN = 'h7';
var TAG_LINE_BREAK = 'br';
var TAG_SELECT = 'select';
var TAG_OPTION = 'option';
var DELIMITER_COLON = ':';
var DELIMITER_PIPE = '|';
var DELIMITER_UNDERSCORE = '_';
var CASING_TITLE = 'CASING';
var COILED_TUBING_TITLE = 'COILED TUBING';
var ATTR_ID = 'id';
var ID_CASING = 'casing';
var ATTR_COLOR = "color";
var ATTR_CLASS = "class";
var ATTR_VALUE = "value";
var ATTR_CX = "cx";
var ATTR_TRANSFORM = 'transform';
var ATTR_CY = 'cy';
var ATTR_X = "x";
var ATTR_Y = "y";
var ATTR_D = 'd';
var ATTR_RADIUS = 'r';
var STYLE_WIDTH = 'width';
var STYLE_HEIGHT = 'height';
var STYLE_OUTLINE = 'outline';
var MAX_BAR_WIDTH = 200;
var SVG_MARGIN = 50, SVG_WIDTH = 750, SVG_HEIGHT = 570;
var FILE_NAME_CASING_METRIC = 'casing_metric.json';
var FILE_NAME_COILED_TUBING = 'coiled_tubing_metric.json';
var KEY_CASING_OD_M = 'od_m',
    KEY_CASING_OD_INCH = 'od_inch',
    KEY_CASING_GRADE = 'grade',
    KEY_CASING_ID_M = 'id_m',
    KEY_CASING_WALL_THICKNESS_M = 'wall_thickness_m',
    KEY_CASING_DRIFT_DIAMETER_M = 'drift_diameter_m',
    KEY_CASING_LSS_M = 'lss_m',
    KEY_CASING_CROSS_SECTIONAL_AREA_M_2 = 'cross_sectional_area_m_2',
    KEY_CASING_NOMINAL_WEIGHT_T_AND_C = 'nominal_weight_t_and_c',
    KEY_CASING_COLLAPSE_PRESSURE = 'collapse_pressure',
    KEY_CASING_INTERNAL_YIELD_PRESSURE = 'internal_yield_pressure',
    KEY_CASING_STC_KPA = 'stc_kpa',
    KEY_CASING_LTC_KPA = 'ltc_kpa',
    KEY_CASING_BTC_KPA = 'btc_kpa',
    KEY_CASING_JOINT_STRENGTH_STC = 'joint_strength_stc',
    KEY_CASING_LTC_N = 'ltc_n',
    KEY_CASING_BTC_N = 'btc_n',
    KEY_CASING_BODY_YIELD_N = 'body_yield_n',
    GRADE_CONFIGURATION_FORMAT = 'Grade ' +
        DELIMITER_PIPE + ' OD(m) ' +
        DELIMITER_PIPE +
        ' ID(m) ' +
        DELIMITER_PIPE + ' Wall Thickness(m) ';
var KEY_COILED_TUBING_OD_M = 'od_m',
    KEY_COILED_TUBING_ID_M = 'id_m',
    KEY_COILED_TUBING_WALL_THICKNESS = 'wall_thickness_m',
    KEY_COILED_TUBING_GRADE = 'grade',
    KEY_COILED_TUBING_OD_INCH = 'od_inch',
    KEY_COILED_TUBING_WEIGHT = 'weight',
    KEY_COILED_TUBING_CROSS_SECTIONAL_AREA_M_2 = 'cross_sectional_area_m_2',
    KEY_COILED_TUBING_PIPE_BODY_YIELD_LOAD_N = 'pipe_body_yield_load_n',
    KEY_COILED_TUBING_TENSILE_LOAD_n = 'tensile_load_n',
    KEY_COILED_TUBING_INTERNAL__YIELD_PRESSURE = 'internal_yield_pressure',
    KEY_COILED_TUBING_HYDRO_TEST_PRESSURE = 'hydro_test_pressure',
    KEY_COILED_TUBING_TORSIONAL_YIELD_STRENGTH_KG_M = 'torsional_yield_strength_kg_m',
    KEY_COILED_TUBING_MINIMUM_YIELD_STRENGTH_K_p_A = 'minimum_yield_strength_k_pa',
    KEY_COILED_TUBING_MINIMUM_TENSILE_STREGTH_K_P_A = 'minimum_tensile_strength_k_pa',
    KEY_COILED_TUBING_HARDNESS = 'hardness';